name: Primetone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#331f1b'
    - '#bfb7ab'
    - '#755645'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
