title: Best Agency Ever
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3102867
  brandStrength: 0.4375
  rhythmicContrast: 0.1382799
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#545a75'
    - '#cdbfbd'
    - '#c76d5a'
  lightness: 0.8254638
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Primetone
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7116358
layout_spectrum: 0.1911028
