name: Primetone
favicon: null
layout_spectrum: 0.57355
typography_spectrum: 0.43648
title: Best Agency Ever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#545a75'
    - '#cdbfbd'
    - '#c76d5a'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
